/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package td;
import java.io.File;
import java.util.ArrayList;

/* Quilodran Jimenez Loris */

public class App {
    
    public static void main(String[] args) {
        ArrayList<File> mesFichiers = new ArrayList<File>();
        compresseur c = new compresseur();
        mesFichiers.add(new File("fichier1.txt"));
        mesFichiers.add(new File("fichier2.txt"));
        c.setFichier(mesFichiers);
        c.creerArchive();

        c.setStrategie(new strategieZIP());
        c.creerArchive();
    }
}
