/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package td;
/* Quilodran Jimenez Loris */
public class App {
    
    public static void main(String[] args) {
        
        /* création d'un login password */ 
        login log = loginManager.factoryLogin("password");

        /* essai avec un mot de passe */
        boolean authentification = log.verify("test", "test123");
        App.checkAuth(authentification);
        /* essai avec un nom de domaine */
        authentification = log.verify("test", "test@test.lan");
        App.checkAuth(authentification);

        /* Création d'un login domain */
        log = loginManager.factoryLogin("domain");
        /* essai avec un mot de passe */
        authentification = log.verify("test", "test123");
        App.checkAuth(authentification);
        /* essai avec un nom de domaine */
        authentification = log.verify("test", "test@test.lan");
        App.checkAuth(authentification);




        
    }


    /* Eviter la répéition de code de vérification */
    public static void checkAuth(boolean auth){
        if(auth) System.out.println("Authentification reussie");
        else System.out.println("Authentification échouée");
    }
}
